"""
This DTO represents the response returned to the frontend
after the AI starts the interview.

Flow:

React
    ↓
POST /start-interview
    ↓
InterviewGenerator Service
    ↓
Gemini
    ↓
InterviewResponse
    ↓
React
"""

from pydantic import BaseModel
from typing import List


class InterviewResponse(BaseModel):
    """
    Response DTO for starting the AI interview.

    Attributes:
        candidate_name (str): Candidate's name extracted from resume.

        greeting (str): Personalized greeting generated by AI.

        questions (List[str]): List of interview questions.
    """

    candidate_name: str

    greeting: str

    questions: List[str]